/**
 * bake-gradient-presets — re-fit the built-in presets to the fewest stops that still draw them.
 *
 * `data/gradientPresets.ts` is GENERATED by this file. The hand-authored colour lists live in
 * SOURCES below and are the only thing to edit; the data file holds the fitted result. Keeping
 * the sources here rather than in the data file is what makes a re-run idempotent: a bake that
 * read its own output would fit a fit, and every run would drift a little further from the
 * palette someone actually designed.
 *
 *   npm run bake:presets          fit SOURCES, write data/gradientPresets.ts, print the table
 *   npm run test:palette-presets  --check: the data file still draws SOURCES within tolerance
 *
 * WHAT A FIT IS. Every consumer applies a preset as `{ stops, colorSpace: 'srgb',
 * blendSpace: 'oklab' }` (grep GRADIENT_PRESETS: registerPaletteUI's Favients seed,
 * presetCatalog, bake-gx-global), so a preset is fitted against its own rendered ramp in that
 * space, in the stop format the app already renders — linear or smooth, with bias. No handles,
 * no new fields: a baked preset is an ordinary gradient.
 *
 * The search is shortest-path over all 256 texels as candidate knots (a segment depends only
 * on its two stop colours plus the left stop's bias and interpolation, so segments are
 * independent and the minimum is exact for this model), with each segment's bias and
 * interpolation chosen from a grid. Measured 2026-09-12 against the shipped greedy `stopFit`
 * over these same 25: 197 stops against 156 at the same tolerance.
 *
 * TOLERANCE. Every texel must land within max(TARGET, half an 8-bit step at that texel) of the
 * source. The floor exists because one 8-bit level in the deep darks is OKLab ΔE ~0.067 — no
 * stop count reaches 0.02 there, and a flat tolerance spends stops arguing with quantisation
 * (grep QUANTISATION_SLACK in palette/core/stopFit.ts for the measurement). HALF a step, not a
 * whole one: at a full step the prototype let Greyscale's darks drift 0.047, which is a visible
 * level; at half, a texel rounds back to the byte it came from.
 *
 * Two deliberate exclusions from the prototype this came from:
 *   - NO STEP SEGMENTS. The prototype placed a step's right knot half a texel early and then
 *     timed the NEXT segment as if it had not, which is where its worst validated errors came
 *     from. These presets are smooth by construction, so steps are simply not offered.
 *   - A PRESET ONLY CHANGES IF IT GETS STRICTLY SMALLER. If the fit would not have fewer stops
 *     than the source, the source is written verbatim — Greyscale is two stops and stays two;
 *     Aurora Strata was hand-tuned with bias and smooth and does not come out smaller. A fit
 *     that fails validation against the real renderer is likewise discarded, never shipped.
 *
 * @see plans/ge-ramp-analysis-and-deep-fit.md Part B — the deep-fit plan this is the first
 *   shipped use of, and (appended 2026-09-13) the measurements behind these numbers.
 */

import fs from 'fs';
import path from 'path';
import type { GradientStop, BlendColorSpace } from '../types';
import { renderStopsToRamp, renderStopsToBuffer, blendLerp, rgbToHex } from '../utils/colorUtils';
import { oklabDistance, type RGB } from '../palette/core/oklab';

/** The fit tolerance, OKLab ΔE. A design decision, so a constant: `--check` must judge the data
 *  file by the same number it was baked at, and a CLI flag would let the two disagree. */
const TARGET = 0.02;
/** How far past the last feasible span the search keeps looking. More can only find fewer
 *  stops, never more; this bake runs offline, so it is generous. */
const MISS_SLACK = 32;
const BIAS = [0.2, 0.26, 0.32, 0.38, 0.44, 0.5, 0.56, 0.62, 0.68, 0.74, 0.8];

// ---------------------------------------------------------------------------------- SOURCES
// Verbatim from data/gradientPresets.ts as of 38caf34e. Order matters: presets are addressed by
// index in places (generatorStore's default slots are 4 = Turbo and 5 = Inferno).

type Source = { name: string; colors: string[] } | { name: string; stops: GradientStop[] };

const SOURCES: Source[] = [
  { name: 'Greyscale', colors: ['#000000', '#ffffff'] },
  { name: 'Grey', colors: ['#7f7f7f', '#696969'] },
  { name: 'Rainbow Divergent', colors: ['#9e0142', '#d53e4f', '#f46d43', '#fdae61', '#fee08b', '#e6f598', '#abdda4', '#66c2a5', '#3288bd', '#5e4fa2'] },
  { name: 'Spectrum', colors: ['#5F4690', '#1D6996', '#38A6A5', '#0F8554', '#73AF48', '#EDAD08', '#E17C05', '#CC503E', '#94346E', '#6F4070', '#994E95', '#666666'] },
  { name: 'Turbo', colors: ['#30123B', '#4145AB', '#4675ED', '#39A2FC', '#1BCFD4', '#24ECA6', '#61FC6C', '#A4FC3B', '#D1E834', '#F3C63A', '#FE9B2D', '#F36315', '#D93806', '#B11901', '#7A0402'] },
  { name: 'Inferno', colors: ['#000004', '#280B54', '#65156E', '#9F2A63', '#D44842', '#F57D15', '#FAC127', '#FCFFA4'] },
  { name: 'Plasma', colors: ['#0D0887', '#5402A3', '#8B0AA5', '#B93289', '#DB5C68', '#F48849', '#FEBC2B', '#F0F921'] },
  { name: 'Viridis', colors: ['#440154', '#46327F', '#365C8D', '#277F8E', '#1FA187', '#4AC26D', '#9FDA3A', '#FDE725'] },
  { name: 'Classic Mandelbrot', colors: ['#421E0F', '#19071A', '#09012F', '#040449', '#000764', '#0C2C8A', '#1852B1', '#397DD1', '#86B5E5', '#D3ECF8', '#F1E9BF', '#F8C95F', '#FFAA00', '#CC8000', '#995700', '#6A3403'] },
  { name: 'Cosmic Energy', colors: ['#00485E', '#005662', '#000000', '#481700', '#803000', '#FFAE55', '#9BF5FF', '#FFFFFF'] },
  { name: 'Lava Lamp', colors: ['#000000', '#001830', '#004060', '#00BFFF', '#006080', '#600000', '#DC0000', '#FF4040'] },
  { name: 'Kindlmann', colors: ['#000000', '#240675', '#073E96', '#077361', '#089F15', '#70C409', '#FAD092', '#FFFFFF'] },
  { name: 'Cool Warm', colors: ['#3B4CC0', '#6889EE', '#9ABAFF', '#C9D8F0', '#EDD1C2', '#F7A889', '#E26A53', '#B40426'] },
  { name: 'Multihue', colors: ['#FD6029', '#698403', '#FFF59B', '#F5BD22', '#0B5E87', '#C68876', '#A51C64', '#3B9FEE', '#D4FFD4', '#ABA53C'] },
  { name: 'Spring Floral', colors: ['#009392', '#39b185', '#9ccb86', '#e9e29c', '#eeb479', '#e88471', '#cf597e'] },
  { name: 'Pastel Dreams', colors: ['#009392', '#72aaa1', '#b1c7b3', '#f1eac8', '#e5b9ad', '#d98994', '#d0587e'] },
  { name: 'Warm Sunset', colors: ['#fcde9c', '#faa476', '#f0746e', '#e34f6f', '#dc3977', '#b9257a', '#7c1d6f'] },
  { name: 'Cool Forest', colors: ['#d3f2a3', '#97e196', '#6cc08b', '#4c9b82', '#217a79', '#105965', '#074050'] },
  { name: 'Earth Tones', colors: ['#3d5941', '#778868', '#b5b991', '#f6edbd', '#edbb8a', '#de8a5a', '#ca562c'] },
  { name: 'Cosine Rainbow', colors: ['#FF8080', '#BFBF0D', '#00FF0D', '#0DBFBF', '#8080FF', '#BF0DBF', '#FF0D0D', '#FF8080'] },
  {
    name: 'Rainbow Full',
    stops: [
      { id: '1', position: 0.0, color: '#ff0000' },
      { id: '2', position: 0.17, color: '#ffff00' },
      { id: '3', position: 0.33, color: '#00ff00' },
      { id: '4', position: 0.5, color: '#00ffff' },
      { id: '5', position: 0.67, color: '#0000ff' },
      { id: '6', position: 0.83, color: '#ff00ff' },
      { id: '7', position: 1.0, color: '#ff0000' },
    ],
  },
  { name: 'Deep Ocean', colors: ['#000764', '#0C2C8A', '#1852B1', '#206BCB', '#397DD1', '#57A5D9', '#86B5E5', '#BAFFFD', '#EDFFFF'] },
  {
    name: 'Neon Cyber',
    stops: [
      { id: '1', position: 0.0, color: '#220033' },
      { id: '2', position: 0.3, color: '#aa00ff' },
      { id: '3', position: 0.7, color: '#00ffcc' },
      { id: '4', position: 1.0, color: '#ffffff' },
    ],
  },
  { name: 'Black Body', colors: ['#000000', '#411712', '#801F1B', '#BC3320', '#E0650A', '#E8A11A', '#E7DA30', '#FFFFFF'] },
  {
    name: 'Aurora Strata',
    stops: [
      { id: '1', position: 0, color: '#000000', bias: 0.7333333333333334, interpolation: 'smooth' },
      { id: '2', position: 0.08849557522123894, color: '#363636', bias: 0.5, interpolation: 'smooth' },
      { id: '3', position: 0.111, color: '#05C1D4', bias: 0.5, interpolation: 'linear' },
      { id: '4', position: 0.18584070796460178, color: '#000000', bias: 0.5, interpolation: 'linear' },
      { id: '5', position: 0.22789970501474927, color: '#FF5500', bias: 0.5, interpolation: 'linear' },
      { id: '6', position: 0.26843657817109146, color: '#FFAB00', bias: 0.5, interpolation: 'linear' },
      { id: '7', position: 0.333, color: '#FFDC7C', bias: 0.5, interpolation: 'linear' },
      { id: '8', position: 0.3746312684365782, color: '#FFFFFF', bias: 0.7551454328967512, interpolation: 'linear' },
      { id: '9', position: 0.444, color: '#3C5732', bias: 0.5, interpolation: 'linear' },
      { id: '10', position: 0.4941474926253687, color: '#97C79D', bias: 0.5, interpolation: 'linear' },
      { id: '11', position: 0.5353510324483777, color: '#FFFFFF', bias: 0.5, interpolation: 'linear' },
      { id: '12', position: 0.667, color: '#000000', bias: 0.5, interpolation: 'linear' },
      { id: '13', position: 0.778, color: '#3B9FEE', bias: 0.5, interpolation: 'linear' },
      { id: '14', position: 0.889, color: '#D4FFD4', bias: 0.5, interpolation: 'linear' },
      { id: '15', position: 1, color: '#FFF659', bias: 0.5, interpolation: 'linear' },
    ],
  },
];

/** Byte-for-byte the helper the data file has always used — positions rounded to 3 decimals —
 *  because a source is only reproduced if it is rendered exactly as it always was. */
const createStops = (colors: string[]): GradientStop[] =>
  colors.map((color, i) => ({ id: `${i}`, position: parseFloat((i / (colors.length - 1)).toFixed(3)), color }));

const sourceStops = (s: Source): GradientStop[] => ('colors' in s ? createStops(s.colors) : s.stops);

// ------------------------------------------------------------------------------------ the fit
type Interp = 'linear' | 'smooth';
interface Seg { interp: Interp; bias: number }

const biasK = (b: number) => (Math.abs(b - 0.5) < 0.001 ? 1 : Math.log(0.5) / Math.log(Math.max(0.001, Math.min(0.999, b))));
const round = (c: RGB): RGB => ({ r: Math.round(c.r), g: Math.round(c.g), b: Math.round(c.b) });

/** OKLab ΔE of one 8-bit step at texel i, in the direction the ramp moves there. */
const quantum = (ramp: RGB[], i: number): number => {
  const a = ramp[Math.max(0, i - 1)];
  const b = ramp[Math.min(255, i + 1)];
  const d = [b.r - a.r, b.g - a.g, b.b - a.b];
  const m = Math.max(Math.abs(d[0]), Math.abs(d[1]), Math.abs(d[2]));
  const p = ramp[i];
  if (m === 0) return oklabDistance(p, { r: Math.min(255, p.r + 1), g: p.g, b: p.b });
  return oklabDistance(p, { r: p.r + d[0] / m, g: p.g + d[1] / m, b: p.b + d[2] / m });
};
const toleranceOf = (ramp: RGB[]): Float64Array => {
  const t = new Float64Array(256);
  for (let i = 0; i < 256; i++) t[i] = Math.max(TARGET, 0.5 * quantum(ramp, i));
  return t;
};

/** Sum of squared ΔE over the span's interior, or Infinity the moment a texel breaks tolerance.
 *  Mirrors `sampleSorted` for stops on integer texels: t = (x-i)/(j-i), then bias, then smooth. */
const segCost = (ramp: RGB[], tol: Float64Array, space: BlendColorSpace, i: number, j: number, s: Seg): number => {
  const k = biasK(s.bias);
  const span = j - i;
  let sum = 0;
  for (let x = i + 1; x < j; x++) {
    let t = (x - i) / span;
    if (k !== 1) t = Math.pow(t, k);
    if (s.interp === 'smooth') t = t * t * (3 - 2 * t);
    const d = oklabDistance(blendLerp(ramp[i], ramp[j], t, space), ramp[x]);
    if (d > tol[x]) return Infinity;
    sum += d * d;
  }
  return sum;
};

/** The best (interp, bias) that holds tolerance over [i, j], or null. */
const bestSeg = (ramp: RGB[], tol: Float64Array, i: number, j: number): Seg | null => {
  if (j === i + 1) return { interp: 'linear', bias: 0.5 };
  let best: Seg | null = null;
  let bestCost = Infinity;
  for (const interp of ['linear', 'smooth'] as Interp[]) {
    for (const bias of BIAS) {
      const c = segCost(ramp, tol, 'oklab', i, j, { interp, bias });
      if (c < bestCost) { bestCost = c; best = { interp, bias }; }
    }
  }
  return best;
};

const fit = (ramp: RGB[], tol: Float64Array): { knots: number[]; segs: Seg[] } => {
  const f = new Float64Array(256).fill(Infinity);
  const nxt = new Int32Array(256).fill(-1);
  const pick: (Seg | null)[] = new Array(256).fill(null);
  f[255] = 0;
  for (let i = 254; i >= 0; i--) {
    let misses = 0;
    for (let j = i + 1; j <= 255; j++) {
      const s = bestSeg(ramp, tol, i, j);
      if (!s) { if (j > i + 1 && ++misses > MISS_SLACK) break; continue; }
      misses = 0;
      if (1 + f[j] < f[i]) { f[i] = 1 + f[j]; nxt[i] = j; pick[i] = s; }
    }
  }
  const knots: number[] = [];
  const segs: Seg[] = [];
  let i = 0;
  while (i >= 0) { knots.push(i); if (nxt[i] < 0) break; segs.push(pick[i]!); i = nxt[i]; }
  return { knots, segs };
};

type Knot = [texel: number, color: string, interpolation: Interp, bias: number];

/** The SAME conversion the generated file's `fromKnots` performs, so validation checks what ships. */
const fromKnots = (knots: Knot[]): GradientStop[] =>
  knots.map(([texel, color, interpolation, bias], i) => ({ id: `${i}`, position: texel / 255, color, bias, interpolation }));

/** Per-texel ΔE of `stops` against the rounded source ramp, through the real renderer. */
const errorsAgainst = (stops: GradientStop[], ramp: RGB[]): number[] => {
  const back = renderStopsToRamp(stops, 'oklab', 'srgb');
  return ramp.map((c, i) => oklabDistance(back[i], c));
};

// ------------------------------------------------------------------------------------- modes
const DATA = path.join(process.cwd(), 'data', 'gradientPresets.ts');
const pad = (s: string | number, n: number) => String(s).padStart(n);
const padr = (s: string | number, n: number) => String(s).padEnd(n);

if (process.argv.includes('--check')) {
  // The data file must still draw every SOURCE within tolerance, in order, with no more stops.
  // Falsified 2026-09-13 two ways: nudging one fitted colour in the data file reds the
  // tolerance assertion; moving a preset out of order reds the name assertion.
  const { GRADIENT_PRESETS } = await import('../data/gradientPresets');
  let failures = 0;
  const fail = (msg: string) => { failures++; console.error('  ✗ ' + msg); };
  if (GRADIENT_PRESETS.length !== SOURCES.length) fail(`${GRADIENT_PRESETS.length} presets, ${SOURCES.length} sources`);
  SOURCES.forEach((src, n) => {
    const p = GRADIENT_PRESETS[n];
    if (!p || p.name !== src.name) return fail(`preset ${n} is "${p?.name}", source is "${src.name}"`);
    // Either the preset IS its source (byte-identical render), or it is a fit held to the
    // tolerance the bake validated it at. The two need different tests: judged against the
    // 8-bit ramp, a verbatim source already reads over tolerance in its darks — float against
    // rounded is up to half a level of pure rounding — so one rule for both failed exactly the
    // five presets that had not changed (measured on the first run of this check).
    const verbatim = (() => {
      const a = renderStopsToBuffer(p.stops, 'oklab', 'srgb');
      const b = renderStopsToBuffer(sourceStops(src), 'oklab', 'srgb');
      return a.every((v, i) => v === b[i]);
    })();
    if (!verbatim) {
      const ramp = renderStopsToRamp(sourceStops(src), 'oklab', 'srgb').map(round);
      const tol = toleranceOf(ramp);
      const errs = errorsAgainst(p.stops, ramp);
      // report the WORST breach, not the first: a nudged knot crosses tolerance a long way before
      // it peaks, and the first texel over reads as a near miss when the change is not one
      let worst = -1;
      errs.forEach((e, i) => { if (e > tol[i] + 1e-9 && (worst < 0 || e - tol[i] > errs[worst] - tol[worst])) worst = i; });
      if (worst >= 0) fail(`${src.name}: texel ${worst} is ΔE ${errs[worst].toFixed(4)} from its source (tolerance ${tol[worst].toFixed(4)}); ${errs.filter((e, i) => e > tol[i] + 1e-9).length} texels over`);
    }
    const srcCount = sourceStops(src).length;
    if (p.stops.length > srcCount) fail(`${src.name}: ${p.stops.length} stops, source has ${srcCount}`);
  });
  const total = GRADIENT_PRESETS.reduce((a, p) => a + p.stops.length, 0);
  const srcTotal = SOURCES.reduce((a, s) => a + sourceStops(s).length, 0);
  console.log(`presets: ${GRADIENT_PRESETS.length} draw their sources within ΔE ${TARGET} (half an 8-bit step in the darks) — ${total} stops against ${srcTotal}`);
  console.log(failures === 0 ? '✓ ALL PASS' : `✗ ${failures} FAILURE(S)`);
  process.exit(failures === 0 ? 0 : 1);
}

console.log(`bake-gradient-presets: ΔE ${TARGET}, half-step floor, no step segments\n`);
console.log(`${padr('preset', 20)} ${pad('src', 4)} ${pad('fit', 4)}  ${padr('ships', 7)} ${pad('change ΔE', 9)}`);
const entries: string[] = [];
let srcTotal = 0;
let outTotal = 0;
for (const src of SOURCES) {
  const stops = sourceStops(src);
  const ramp = renderStopsToRamp(stops, 'oklab', 'srgb').map(round);
  const tol = toleranceOf(ramp);
  const { knots, segs } = fit(ramp, tol);
  const k: Knot[] = knots.map((t, m) => {
    const color = rgbToHex(ramp[t]).toUpperCase();
    // A segment between two IDENTICAL colours draws the same whatever its bias or
    // interpolation, so the grid's pick there is noise — written plain rather than shipping a
    // number that means nothing (Black Body's first segment is black to black).
    const flat = m < segs.length && color === rgbToHex(ramp[knots[m + 1]]).toUpperCase();
    return m < segs.length && !flat ? [t, color, segs[m].interp, segs[m].bias] : [t, color, 'linear', 0.5];
  });
  const fitted = fromKnots(k);
  const errs = errorsAgainst(fitted, ramp);
  const valid = errs.every((e, i) => e <= tol[i] + 1e-9);
  const smaller = fitted.length < stops.length;
  const ships = valid && smaller;
  srcTotal += stops.length;
  outTotal += ships ? fitted.length : stops.length;
  // The CHANGE a user can see: what ships against the source, both rendered as floats. Against
  // the 8-bit ramp even a verbatim source reads ~0.05 in the darks, which is rounding, not change.
  const srcFloat = renderStopsToRamp(stops, 'oklab', 'srgb');
  const outFloat = renderStopsToRamp(ships ? fitted : stops, 'oklab', 'srgb');
  const change = Math.max(...srcFloat.map((c, i) => oklabDistance(c, outFloat[i])));
  console.log(`${padr(src.name, 20)} ${pad(stops.length, 4)} ${pad(fitted.length, 4)}  ${padr(ships ? 'fitted' : valid ? 'source' : 'SOURCE!', 7)} ${pad(change.toFixed(4), 9)}`);
  if (!valid) console.log(`  (the fit broke tolerance against the real renderer, so the source ships)`);

  const name = `'${src.name.replace(/'/g, "\\'")}'`;
  if (ships) {
    const rows = k.map(([t, c, interp, bias]) => `[${t}, '${c}'${interp === 'linear' && bias === 0.5 ? '' : `, '${interp}', ${bias}`}]`);
    entries.push(`  { name: ${name}, stops: fromKnots([${rows.join(', ')}]) },`);
  } else if ('colors' in src) {
    entries.push(`  { name: ${name}, stops: createStops([${src.colors.map((c) => `'${c}'`).join(', ')}]) },`);
  } else {
    const lit = (v: unknown) => (typeof v === 'string' ? `'${v}'` : String(v));
    const rows = src.stops.map((st) => `      { ${Object.entries(st).map(([key, v]) => `${key}: ${lit(v)}`).join(', ')} },`);
    entries.push(`  {\n    name: ${name},\n    stops: [\n${rows.join('\n')}\n    ],\n  },`);
  }
}

const out = `/**
 * The built-in gradient presets.
 *
 * GENERATED by debug/bake-gradient-presets.mts — do not hand-edit. The hand-authored colour
 * lists live in that file's SOURCES; change them there and run \`npm run bake:presets\`.
 *
 * Each preset is its source re-fitted to the fewest stops that still draw it: every texel within
 * OKLab ΔE ${TARGET} of the source's rendered ramp (or half an 8-bit step, where that is larger
 * — the deep darks), in the format the app already renders, with blendSpace 'oklab' as every
 * consumer applies it. A preset whose fit would not have been strictly smaller keeps its source
 * verbatim. ${outTotal} stops across the ${SOURCES.length}, against ${srcTotal} in the sources.
 *
 * Addressed by INDEX in places (generatorStore's default slots are 4 = Turbo, 5 = Inferno), so
 * SOURCES order is load-bearing.
 *
 * Guard: \`npm run test:palette-presets\` — this file still draws SOURCES within tolerance, in
 * order, with no preset larger than its source.
 */

import type { GradientStop } from '../types';

export interface GradientPreset {
  name: string;
  stops: GradientStop[];
}

/** An evenly spaced colour list — how the sources are authored, and how a preset the fit could
 *  not shrink is written. Positions round to 3 decimals, as they always have. */
const createStops = (colors: string[]): GradientStop[] =>
  colors.map((color, i) => ({ id: \`\${i}\`, position: parseFloat((i / (colors.length - 1)).toFixed(3)), color }));

/** A fitted preset: [texel 0..255, colour, interpolation?, bias?]. The position is \`texel / 255\`
 *  EXACTLY — the fit placed every stop on a texel, and rounding a position would move it off one. */
const fromKnots = (knots: ReadonlyArray<readonly [number, string, ('linear' | 'smooth')?, number?]>): GradientStop[] =>
  knots.map(([texel, color, interpolation = 'linear', bias = 0.5], i) => ({ id: \`\${i}\`, position: texel / 255, color, bias, interpolation }));

export const GRADIENT_PRESETS: GradientPreset[] = [
${entries.join('\n')}
];
`;

fs.writeFileSync(DATA, out, 'utf8');
console.log(`\n${outTotal} stops against ${srcTotal} (${(((srcTotal - outTotal) / srcTotal) * 100).toFixed(0)}% fewer) → ${path.relative(process.cwd(), DATA)}`);
