/**
 * The built-in gradient presets.
 *
 * GENERATED by debug/bake-gradient-presets.mts — do not hand-edit. The hand-authored colour
 * lists live in that file's SOURCES; change them there and run `npm run bake:presets`.
 *
 * Each preset is its source re-fitted to the fewest stops that still draw it: every texel within
 * OKLab ΔE 0.02 of the source's rendered ramp (or half an 8-bit step, where that is larger
 * — the deep darks), in the format the app already renders, with blendSpace 'oklab' as every
 * consumer applies it. A preset whose fit would not have been strictly smaller keeps its source
 * verbatim. 154 stops across the 25, against 209 in the sources.
 *
 * Addressed by INDEX in places (generatorStore's default slots are 4 = Turbo, 5 = Inferno), so
 * SOURCES order is load-bearing.
 *
 * Guard: `npm run test:palette-presets` — this file still draws SOURCES within tolerance, in
 * order, with no preset larger than its source.
 */

import type { GradientStop } from '../types';

export interface GradientPreset {
  name: string;
  stops: GradientStop[];
}

/** An evenly spaced colour list — how the sources are authored, and how a preset the fit could
 *  not shrink is written. Positions round to 3 decimals, as they always have. */
const createStops = (colors: string[]): GradientStop[] =>
  colors.map((color, i) => ({ id: `${i}`, position: parseFloat((i / (colors.length - 1)).toFixed(3)), color }));

/** A fitted preset: [texel 0..255, colour, interpolation?, bias?]. The position is `texel / 255`
 *  EXACTLY — the fit placed every stop on a texel, and rounding a position would move it off one. */
const fromKnots = (knots: ReadonlyArray<readonly [number, string, ('linear' | 'smooth')?, number?]>): GradientStop[] =>
  knots.map(([texel, color, interpolation = 'linear', bias = 0.5], i) => ({ id: `${i}`, position: texel / 255, color, bias, interpolation }));

export const GRADIENT_PRESETS: GradientPreset[] = [
  { name: 'Greyscale', stops: createStops(['#000000', '#ffffff']) },
  { name: 'Grey', stops: createStops(['#7f7f7f', '#696969']) },
  { name: 'Rainbow Divergent', stops: fromKnots([[0, '#9E0142'], [23, '#CB354D', 'linear', 0.56], [85, '#FDAE61', 'smooth', 0.38], [133, '#EFEF92', 'linear', 0.62], [188, '#7FCCA4'], [255, '#5E4FA2']]) },
  { name: 'Spectrum', stops: fromKnots([[0, '#5F4690'], [16, '#365F9A', 'linear', 0.62], [44, '#2FA0A5', 'linear', 0.62], [67, '#08895E', 'linear', 0.62], [86, '#59A34E'], [114, '#E4AE00', 'linear', 0.56], [172, '#B84058', 'smooth', 0.38], [202, '#793D72', 'smooth', 0.68], [228, '#924C8F', 'smooth', 0.62], [255, '#666666']]) },
  { name: 'Turbo', stops: fromKnots([[0, '#30123B'], [19, '#4247AE', 'linear', 0.44], [46, '#3D8DF6', 'linear', 0.62], [64, '#00BCE8', 'linear', 0.32], [122, '#92FC4C', 'linear', 0.62], [171, '#F9B52C'], [208, '#E8520D', 'linear', 0.56], [255, '#7A0402']]) },
  { name: 'Inferno', stops: fromKnots([[0, '#000004', 'linear', 0.44], [49, '#3B0F60'], [191, '#F98E00'], [255, '#FCFFA4']]) },
  { name: 'Plasma', stops: fromKnots([[0, '#0D0887'], [51, '#6A06A6', 'linear', 0.56], [152, '#E16362'], [255, '#F0F921']]) },
  { name: 'Viridis', stops: fromKnots([[0, '#440154'], [85, '#2C6890'], [182, '#4AC26D'], [255, '#FDE725']]) },
  { name: 'Classic Mandelbrot', stops: fromKnots([[0, '#421E0F'], [13, '#240A1B', 'linear', 0.38], [29, '#100329'], [56, '#030551', 'linear', 0.62], [103, '#1A55B3', 'linear', 0.56], [152, '#CEE9F7'], [168, '#E7ECC5', 'smooth', 0.44], [199, '#FDB42D', 'linear', 0.56], [255, '#6A3403']]) },
  { name: 'Cosmic Energy', stops: createStops(['#00485E', '#005662', '#000000', '#481700', '#803000', '#FFAE55', '#9BF5FF', '#FFFFFF']) },
  { name: 'Lava Lamp', stops: createStops(['#000000', '#001830', '#004060', '#00BFFF', '#006080', '#600000', '#DC0000', '#FF4040']) },
  { name: 'Kindlmann', stops: createStops(['#000000', '#240675', '#073E96', '#077361', '#089F15', '#70C409', '#FAD092', '#FFFFFF']) },
  { name: 'Cool Warm', stops: fromKnots([[0, '#3B4CC0'], [35, '#6687EC', 'linear', 0.44], [103, '#C0D3F3', 'smooth', 0.56], [139, '#EFCECC', 'smooth', 0.56], [169, '#F4B79C', 'linear', 0.56], [255, '#B40426']]) },
  { name: 'Multihue', stops: createStops(['#FD6029', '#698403', '#FFF59B', '#F5BD22', '#0B5E87', '#C68876', '#A51C64', '#3B9FEE', '#D4FFD4', '#ABA53C']) },
  { name: 'Spring Floral', stops: fromKnots([[0, '#009392'], [17, '#0CA08F', 'linear', 0.56], [124, '#E3E099'], [255, '#CF597E']]) },
  { name: 'Pastel Dreams', stops: fromKnots([[0, '#009392'], [34, '#64A69D', 'linear', 0.56], [121, '#E6E5C4', 'smooth', 0.68], [168, '#E6BBAD', 'linear', 0.44], [255, '#D0587E']]) },
  { name: 'Warm Sunset', stops: fromKnots([[0, '#FCDE9C'], [23, '#FDBF81', 'linear', 0.38], [150, '#E04473', 'linear', 0.62], [255, '#7C1D6F']]) },
  { name: 'Cool Forest', stops: fromKnots([[0, '#D3F2A3'], [21, '#B7EA9B'], [255, '#074050']]) },
  { name: 'Earth Tones', stops: fromKnots([[0, '#3D5941'], [123, '#EFE7B8', 'smooth', 0.8], [136, '#F4E3B1'], [255, '#CA562C']]) },
  { name: 'Cosine Rainbow', stops: createStops(['#FF8080', '#BFBF0D', '#00FF0D', '#0DBFBF', '#8080FF', '#BF0DBF', '#FF0D0D', '#FF8080']) },
  {
    name: 'Rainbow Full',
    stops: [
      { id: '1', position: 0, color: '#ff0000' },
      { id: '2', position: 0.17, color: '#ffff00' },
      { id: '3', position: 0.33, color: '#00ff00' },
      { id: '4', position: 0.5, color: '#00ffff' },
      { id: '5', position: 0.67, color: '#0000ff' },
      { id: '6', position: 0.83, color: '#ff00ff' },
      { id: '7', position: 1, color: '#ff0000' },
    ],
  },
  { name: 'Deep Ocean', stops: fromKnots([[0, '#000764'], [71, '#1A58B7', 'linear', 0.56], [174, '#6EACDF', 'smooth', 0.56], [231, '#C8FFFE'], [255, '#EDFFFF']]) },
  {
    name: 'Neon Cyber',
    stops: [
      { id: '1', position: 0, color: '#220033' },
      { id: '2', position: 0.3, color: '#aa00ff' },
      { id: '3', position: 0.7, color: '#00ffcc' },
      { id: '4', position: 1, color: '#ffffff' },
    ],
  },
  { name: 'Black Body', stops: fromKnots([[0, '#000000'], [5, '#000000', 'linear', 0.32], [58, '#651D17', 'linear', 0.44], [123, '#CA461A'], [221, '#E8DD4A'], [255, '#FFFFFF']]) },
  {
    name: 'Aurora Strata',
    stops: [
      { id: '1', position: 0, color: '#000000', bias: 0.7333333333333334, interpolation: 'smooth' },
      { id: '2', position: 0.08849557522123894, color: '#363636', bias: 0.5, interpolation: 'smooth' },
      { id: '3', position: 0.111, color: '#05C1D4', bias: 0.5, interpolation: 'linear' },
      { id: '4', position: 0.18584070796460178, color: '#000000', bias: 0.5, interpolation: 'linear' },
      { id: '5', position: 0.22789970501474927, color: '#FF5500', bias: 0.5, interpolation: 'linear' },
      { id: '6', position: 0.26843657817109146, color: '#FFAB00', bias: 0.5, interpolation: 'linear' },
      { id: '7', position: 0.333, color: '#FFDC7C', bias: 0.5, interpolation: 'linear' },
      { id: '8', position: 0.3746312684365782, color: '#FFFFFF', bias: 0.7551454328967512, interpolation: 'linear' },
      { id: '9', position: 0.444, color: '#3C5732', bias: 0.5, interpolation: 'linear' },
      { id: '10', position: 0.4941474926253687, color: '#97C79D', bias: 0.5, interpolation: 'linear' },
      { id: '11', position: 0.5353510324483777, color: '#FFFFFF', bias: 0.5, interpolation: 'linear' },
      { id: '12', position: 0.667, color: '#000000', bias: 0.5, interpolation: 'linear' },
      { id: '13', position: 0.778, color: '#3B9FEE', bias: 0.5, interpolation: 'linear' },
      { id: '14', position: 0.889, color: '#D4FFD4', bias: 0.5, interpolation: 'linear' },
      { id: '15', position: 1, color: '#FFF659', bias: 0.5, interpolation: 'linear' },
    ],
  },
];
